var DatosAvance = [
    {
        "IdEdicion": "1",
        "IdEstado": "1",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Incipiente",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "2",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "3",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Intermedio",
        "5": "Mayor avance",
        "6": "Mayor avance",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "4",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Intermedio",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "5",
        "1": "Mayor avance",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Incipiente",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "6",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Mayor avance",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "7",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Mayor avance",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "8",
        "1": "Mayor avance",
        "2": "Intermedio",
        "3": "Intermedio",
        "4": "Intermedio",
        "5": "Intermedio",
        "6": "Mayor avance",
        "7": "Mayor avance",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "9",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Intermedio",
        "6": "Incipiente",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "10",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Incipiente",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "11",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Intermedio",
        "7": "Mayor avance",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "12",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Mayor avance",
        "7": "Mayor avance",
        "8": "Mayor avance",
        "9": "Mayor avance",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "13",
        "1": "Incipiente",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Intermedio",
        "6": "Intermedio",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "14",
        "1": "Intermedio",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Intermedio",
        "5": "Intermedio",
        "6": "Intermedio",
        "7": "Mayor avance",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "15",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Intermedio",
        "5": "Mayor avance",
        "6": "Intermedio",
        "7": "Mayor avance",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "16",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "17",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "18",
        "1": "Incipiente",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Intermedio",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "19",
        "1": "Mayor avance",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Intermedio",
        "7": "Intermedio",
        "8": "Intermedio",
        "9": "Intermedio",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "20",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Mayor avance",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "21",
        "1": "Mayor avance",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "22",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Intermedio",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "23",
        "1": "Mayor avance",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Incipiente",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "24",
        "1": "Mayor avance",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Incipiente",
        "5": "Intermedio",
        "6": "Incipiente",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "25",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Intermedio",
        "5": "Incipiente",
        "6": "Intermedio",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "26",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Mayor avance",
        "4": "Intermedio",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Mayor avance",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "27",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Intermedio",
        "5": "Incipiente",
        "6": "Mayor avance",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "28",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Mayor avance",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Intermedio",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "29",
        "1": "Incipiente",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Intermedio",
        "7": "Incipiente",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "30",
        "1": "Mayor avance",
        "2": "Incipiente",
        "3": "Intermedio",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Mayor avance",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Mayor avance",
        "10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "31",
        "1": "Intermedio",
        "2": "Mayor avance",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Mayor avance",
        "6": "Intermedio",
        "7": "Incipiente",
        "8": "Intermedio",
        "9": "Mayor avance",
        "10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "32",
        "1": "Intermedio",
        "2": "Incipiente",
        "3": "Incipiente",
        "4": "Mayor avance",
        "5": "Incipiente",
        "6": "Incipiente",
        "7": "Intermedio",
        "8": "Incipiente",
        "9": "Incipiente",
        "10": "Intermedio"
    }
];