var DatosAvance = [
    {
        "IdEdicion": "1",
        "IdEstado": "1",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Incipiente",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "2",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "3",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "4",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "5",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Incipiente",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "6",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "7",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "8",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Intermedio",
        "Dimensión 3": "Intermedio",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Intermedio",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Mayor avance",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "9",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Intermedio",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "10",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Incipiente",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "11",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Mayor avance",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "12",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Mayor avance",
        "Dimensión 8": "Mayor avance",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "13",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Intermedio",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "14",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Intermedio",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Mayor avance",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "15",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Mayor avance",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "16",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "17",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "18",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "19",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Intermedio",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "20",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "21",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "22",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Intermedio",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "23",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "24",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Incipiente",
        "Dimensión 5": "Intermedio",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "25",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Intermedio"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "26",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Mayor avance",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Mayor avance",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "27",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Intermedio",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "28",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Intermedio",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "29",
        "Dimensión 1": "Incipiente",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "30",
        "Dimensión 1": "Mayor avance",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Intermedio",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Mayor avance",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Incipiente"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "31",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Mayor avance",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Mayor avance",
        "Dimensión 6": "Intermedio",
        "Dimensión 7": "Incipiente",
        "Dimensión 8": "Intermedio",
        "Dimensión 9": "Mayor avance",
        "Dimensión 10": "Mayor avance"
    },
    {
        "IdEdicion": "1",
        "IdEstado": "32",
        "Dimensión 1": "Intermedio",
        "Dimensión 2": "Incipiente",
        "Dimensión 3": "Incipiente",
        "Dimensión 4": "Mayor avance",
        "Dimensión 5": "Incipiente",
        "Dimensión 6": "Incipiente",
        "Dimensión 7": "Intermedio",
        "Dimensión 8": "Incipiente",
        "Dimensión 9": "Incipiente",
        "Dimensión 10": "Intermedio"
    }
];